apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: dockerusertwo/testrepo2025:1.0.0-RELEASE
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 8080