apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: <docker-hub-image-url> 
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 8080
